name: Build .NET Project

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x' 

      - name: Restauração de dependências
        run: dotnet restore

      - name: Compilar o projeto (script personalizado)
        run: dotnet build --no-restore --configuration Release
