name: Workflow Push

on:

  push:
    branches:
      - main  


  schedule:
    - cron: '0 * * * *'  # A cada hora

jobs:
  exemplo-job:
    runs-on: ubuntu-latest 

    steps:
   
      - name: Check out the repository
        uses: actions/checkout@v2


      - name: Display a message
        run: echo "O workflow foi executado!"
