name: Workflow  para push

on:

  push:
    branches:
      - main  


  schedule:
    - cron: '0 * * * *'  

jobs:
  exemplo-job:
    runs-on: ubuntu-latest  

    steps:

      - name: Check out the repository
        uses: actions/checkout@v2

 
      - name: Display a message
        run: echo "Workflow foi executado com sucesso!"

   
      - name: Create a log file
        run: echo "Este é um log gerado pelo workflow." > log.txt


      - name: Upload log file
        uses: actions/upload-artifact@v2
        with:
          name: log
          path: log.txt

